### PR TITLE
Make testimonials responsive to different card heights

### PR DESCRIPTION
**Pull request by clemmy**
Addresses https://github.com/ZooHouse/zh-landing/issues/28

See the code that I jipped: https://coderwall.com/p/uf2pka/normalize-twitter-bootstrap-carousel-slide-heights

There seems to be a bug sometimes when resizing the browser window quickly...not sure if that's a bug with the code I took or with the browser not firing enough resize events.

### CODE REVIEW

**Comment by raywan** [comment]
screen shot 2016-08-26 at 7 07 10 pm

Is it horizontally centred for you?

**Comment by clemmy** [comment]
@raywan Shoot, there's a bug in the JS where all the heights except for the active item's height is `0px`... This causes the first active item's height to be the `tallest` in the normalization. I just pushed a temporary patch, but if you can help me look into it today, that'd be great.

**Comment by clemmy** [comment]
Just tried something like

```
          function normalizeHeights() {
              items.each(function() { //add heights to array
                  var height = $(this).find('.testimonial-wrapper').height();
                  if (height <= 0) {
                      console.log($('#testimonials-carousel .item.active'))
                      $('#testimonials-carousel .item.active').append('<div id="tempContainer" style="visibility:hidden;position:absolute;overflow:hidden;"></div>');
                      var carouselItem = $(this).find('.testimonial-wrapper')[0].cloneNode(true);
                      $('#tempContainer').append(carouselItem)
                      height = $('#tempContainer .testimonial-wrapper').height();
                      $('#tempContainer').remove()
                  }
                  heights.push(height);
              });
              tallest = Math.max.apply(null, heights); //cache largest value
              items.each(function() {
                  $(this).css('min-height',tallest + 'px');
              });
          };
```

in order to get heights for other carousel items but this approach isn't giving correct heights.

**Comment by ntimpham** [comment]
Lol this looks to crazy for me. Some crazy magic going on.

**Comment by clemmy** [comment]
new PR https://github.com/ZooHouse/zh-landing/pull/49

**Pull request closed without merging**
