### PR TITLE
Mobile friendly landing

### PR DESCRIPTION
**Pull request by clemmy**
Addresses https://github.com/ZooHouse/zh-landing/issues/38

### CODE REVIEW

**Comment by ntimpham** [comment]
Looks good I guess. Need Ray to confirm.

**Comment by raywan** [comment]
LGTM

**Comment by clemmy** [comment]
kk, let's push danny for an actual landing image before I merge this in and deploy

**Review by ntimpham — APPROVED** [review]
Maybe have a different photo kek

**Pull request closed without merging**
